version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:2023.10.1  # Use CircleCI Android image with Android SDK tools
    working_directory: ~/repo
    environment:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:$PATH

jobs:
  build:
    executor: android
    steps:
      # Step 1: Checkout code
      - checkout

      # Step 2: Install required utilities
      - run:
          name: Install required utilities (curl, yes, unzip)
          command: |
            apt-get update && apt-get install -y curl unzip coreutils
            # Ensure sdkmanager is available and update SDK
            yes | sdkmanager --update

      # Step 3: Install Android SDK components
      - run:
          name: Install Android SDK components
          command: |
            # Install SDK components
            sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.0"
            # Accept SDK licenses
            yes | sdkmanager --licenses

      # Step 4: Make gradlew executable
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      # Step 5: Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-

      # Step 6: Install Gradle dependencies
      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      # Step 7: Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      # Step 8: Build APK
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease

      # Step 9: Store APK as an artifact
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: apk

workflows:
  version: 2
  build:
    jobs:
      - build
