version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-30-alpine  # Alpine-based image
    working_directory: ~/repo

jobs:
  build:
    executor: android
    steps:
      - checkout

      # Step to install necessary dependencies (apk for Alpine-based image)
      - run:
          name: Install dependencies (curl, unzip, coreutils)
          command: |
            apk update
            apk add curl unzip coreutils

      # Other steps in your build process go here
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: apk
