version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-30  # Use the appropriate CircleCI Android image
    working_directory: ~/repo

jobs:
  build:
    executor: android
    steps:
      - checkout

      # Step to install necessary dependencies
      - run:
          name: Install dependencies (curl, unzip, coreutils)
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip coreutils

      # Other steps in your build process go here
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: apk
