version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:2023.10.1  # CircleCI Android Docker image
    working_directory: ~/repo
    environment:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:$PATH

jobs:
  build:
    executor: android
    steps:
      # Step 1: Checkout code
      - checkout

      # Step 2: Install necessary tools and Android SDK
      - run:
          name: Install curl, unzip, and Android SDK
          command: |
            # Use root permissions to install curl and unzip (if necessary)
            apt update && apt install -y curl unzip

            # Download and install Android SDK command-line tools
            curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
            mkdir -p /opt/android-sdk/cmdline-tools
            unzip sdk-tools.zip -d /opt/android-sdk/cmdline-tools
            rm sdk-tools.zip
            mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest

            # Install platform-tools and Android 33 platform
            /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk --install "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      # Step 3: Make Gradle wrapper executable
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      # Step 4: Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-

      # Step 5: Install Gradle dependencies
      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      # Step 6: Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      # Step 7: Build APK
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease

      # Step 8: Store APK as an artifact
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: apk

workflows:
  version: 2
  build:
    jobs:
      - build
