version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-30  # Use an appropriate CircleCI Android image
    working_directory: ~/repo

jobs:
  build:
    executor: android
    steps:
      # Step 1: Checkout code
      - checkout

      # Step 2: Make gradlew executable
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      # Step 3: Restore Gradle dependencies
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-

      # Step 4: Set up dependencies
      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      # Step 5: Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      # Step 6: Build APK
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease

      # Step 7: Store artifacts (APK)
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: apk

workflows:
  version: 2
  build:
    jobs:
      - build
