version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:2023.10.1  # Use an appropriate CircleCI Android image
    working_directory: ~/repo
    environment:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:$PATH

jobs:
  build:
    executor: android
    steps:
      # Step 1: Checkout code
      - checkout
      - run:
          name: Install Android SDK
          command: |
            apt-get update && apt-get install -y curl unzip
            
            # Download and install Android SDK command-line tools
            curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
            mkdir -p /opt/android-sdk/cmdline-tools
            unzip sdk-tools.zip -d /opt/android-sdk/cmdline-tools
            rm sdk-tools.zip
            mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
            
            # Install SDK platform-tools and Android 33 platform
            /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android-sdk --install "platform-tools" "platforms;android-33"
      

      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      # Step 2: Restore Gradle dependencies
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-

      # Step 3: Set up dependencies
      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      # Step 4: Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      # Step 5: Build APK
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: apk